version: 1.2
workflows:
- name: QIIME2-Ia import multiplexed data single end
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /QIIME2-Ia-multiplexed-data-single-end.ga
  testParameterFiles:
  - /QIIME2-Ia-multiplexed-data-single-end-tests.yml
  authors:
  - name: Debjyoti Ghosh
    orcid: 0009-0008-1496-1677
  - name: "Helmholtz-Zentrum für Umweltforschung - UFZ"
    address: "Permoserstraße 15, 04318 Leipzig"
- name: QIIME2-Ib import multiplexed data paired end
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /QIIME2-Ib-multiplexed-data-paired-end.ga
  testParameterFiles:
  - /QIIME2-Ib-multiplexed-data-paired-end-tests.yml
  authors:
  - name: Debjyoti Ghosh
    orcid: 0009-0008-1496-1677
  - name: "Helmholtz-Zentrum für Umweltforschung - UFZ"
    address: "Permoserstraße 15, 04318 Leipzig"
- name: QIIME2-Ic import demultiplexed data single end
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /QIIME2-Ic-demultiplexed-data-single-end.ga
  testParameterFiles:
  - /QIIME2-Ic-demultiplexed-data-single-end-tests.yml
  authors:
  - name: Debjyoti Ghosh
    orcid: 0009-0008-1496-1677
  - name: "Helmholtz-Zentrum für Umweltforschung - UFZ"
    address: "Permoserstraße 15, 04318 Leipzig"
- name: QIIME2-Id import demultiplexed data paired end
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /QIIME2-Id-demultiplexed-data-paired-end.ga
  testParameterFiles:
  - /QIIME2-Id-demultiplexed-data-paired-end-tests.yml
  authors:
  - name: Debjyoti Ghosh
    orcid: 0009-0008-1496-1677
  - name: "Helmholtz-Zentrum für Umweltforschung - UFZ"
    address: "Permoserstraße 15, 04318 Leipzig"

